version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:root@db:5432/mydb?schema=public
      - JWT_SECRET=your-production-secret-key
      - JWT_EXPIRES_IN=1h
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16.8-alpine3.20
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
